version: '3.8'  
services:  
  databases:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 4030d30b5349e18d0c46945246f996aa1e2013378d6de5d4bd6d0b08 
  webserver:
    image: nginx
    ports:
    - "8090:80"
